### ISSUE TITLE
You forgot to put css in your repo!

### ISSUE THREAD

**Issue by austinhuang0131** [simonguozirui/simonguozirui.github.io#3]
index.html, line 19:
```css
	    <link rel="stylesheet" href="css/bootstrap.css">
```
This file doesn't exist.

---
index.html, line 21:
```css
	    <link rel='stylesheet' href='css/index.css'>
```
This file doesn't exist.

**Comment by simonguozirui** [comment]
i just changed all my set up

*Simon Zirui Guo* | * 郭子睿*
Grade 10 High School Student at Upper Canada College
Event Coordinator at Toronto Hacker Club
Toronto, Ontario, Canada
E-mail: simonguozirui@gmail.com
Phone: (647) 972-1505
Website: simonguo.tech
LinkedIn: https://ca.linkedin.com/in/simon-guo-427b4a112

**Comment by simonguozirui** [comment]
i am changing my css framework lol
